"""Added the is_librarian model

Revision ID: 096b116017ca
Revises: 320104fc898b
Create Date: 2025-06-10 13:27:17.889798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096b116017ca'
down_revision = '320104fc898b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_librarian', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_librarian')

    # ### end Alembic commands ###
