"""Add new features

Revision ID: 157c57ca1a85
Revises: e27afa3f9e2c
Create Date: 2025-05-31 21:58:11.642552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157c57ca1a85'
down_revision = 'e27afa3f9e2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_borrow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrowed_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_borrow', schema=None) as batch_op:
        batch_op.drop_column('due_date')
        batch_op.drop_column('borrowed_date')

    # ### end Alembic commands ###
