"""Add new features

Revision ID: e27afa3f9e2c
Revises: a5976dd9ee34
Create Date: 2025-05-31 17:13:03.048248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e27afa3f9e2c'
down_revision = 'a5976dd9ee34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sales_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('sales_count')

    # ### end Alembic commands ###
