"""Add membership_fee column to Member

Revision ID: f73749cfa324
Revises: eb9be4a76a40
Create Date: 2025-06-05 16:16:24.040604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f73749cfa324'
down_revision = 'eb9be4a76a40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('membership_fee', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_column('membership_fee')

    # ### end Alembic commands ###
